version: '3.9'

services:
#  kamailio:
#    container_name: sip_dev_kamailio
#    image: kamailio/kamailio-ci
#    network_mode: host
#    volumes:
#      - ./docker/kamailio:/etc/kamailio

  kamailio:
    container_name: sip_dev_kamailio
    build:
      context: .
      dockerfile: docker/kamailio/Dockerfile
    network_mode: host
    volumes:
      - ./docker/kamailio:/etc/kamailio

  db:
    container_name: sip_dev_postgres
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "toor"
    volumes:
      - sip_dev_postgres:/var/lib/postgresql/data
    networks:
      sip_dev_network:
        ipv4_address: 172.28.12.2

  rtpengine:
    container_name: sip_dev_rtpengine
    image: fonoster/rtpengine:latest
    network_mode: host
    volumes:
      - ./docker/rtpengine/rtpengine.conf:/etc/rtpengine/rtpengine.conf
    command: rtpengine --config-file=/etc/rtpengine/rtpengine.conf --foreground

volumes:
  sip_dev_postgres:

networks:
  sip_dev_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.12.0/29
          gateway: 172.28.12.1
